MarginReportEntry bug fix
tastyware/tastytrade pull request #145
Opened 2024-05-11 11:41 UTC by Quenos

## Description
Account.MarginEntryReport changed to also handle options on futures correctly.
Some fields were made Optional

## Related issue(s)
Fixes 144

## Pre-merge checklist
- [ ] Passing tests LOCALLY
- [ ] New tests added (if applicable)

Please note that, in order to pass the tests, you'll need to set up your Tastytrade credentials as repository secrets on your local fork. Read more at CONTRIBUTING.md.

2024-05-11 15:44 UTC, Graeme22 requested changes

2024-05-11 15:44 UTC, Graeme22 commented on tastytrade/account.py
> +    point_of_no_return_percent: Decimal
I believe this needs to be optional, I don't remember under what conditions it can be none but anything that's optional is optional for a reason

2024-05-11 17:38 UTC, Graeme22 approved these changes

2024-05-12 16:28 UTC, merged

2024-05-12 16:29 UTC, Graeme22 commented
Thanks @Quenos !

2024-05-12 16:52 UTC, Quenos commented
Sure thing!
BTW: I don’t know if you’ve seen it but the advanced-streamer branch is also available.

--
Best regards,
Coen Kuijpers
Automotive Functional Safety Expert
Tel:        +31 6 4463 1722 (The Netherlands)
                +36 70 789 3142 (Hungary)

[signature_157047780]

From: Graeme Holliday ***@***.***>
Date: Sunday, May 12, 2024 at 6:29 PM
To: tastyware/tastytrade ***@***.***>
Cc: Coen Kuijpers ***@***.***>, Mention ***@***.***>
Subject: Re: [tastyware/tastytrade] MarginReportEntry bug fix (PR #145)

Thanks @Quenos<https://github.com/Quenos> !

—
Reply to this email directly, view it on GitHub<https://github.com/tastyware/tastytrade/pull/145#issuecomment-2106307373>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AIKO67IQTF35LYAJQZPJHELZB6KHHAVCNFSM6AAAAABHR3RGW6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBWGMYDOMZXGM>.
You are receiving this because you were mentioned.Message ID: ***@***.***>