Attributes made optional in class MarketMetricInfo(TastytradeJsonDataclass)
tastyware/tastytrade pull request #78
Opened 2023-07-26 07:44 UTC by Quenos

## Description

## Related issue(s)
Fixes ...

## Pre-merge checklist
- [ ] Passing tests
- [ ] New tests added (if applicable)

2023-07-26 16:23 UTC, Graeme22 requested changes
Hi, I appreciate the changes but there's a lot of unnecessary things and style modifications. I won't be able to accept this unless it's passing the tests and matches the rest of the project.

2023-07-26 16:23 UTC, Graeme22 commented on tastytrade/metrics.py
> -from typing import Any, Dict, List, Optional
This is important for supporting earlier versions of Python

2023-07-26 16:23 UTC, Graeme22 commented on tastytrade/metrics.py
> -    created_at: Optional[datetime] = None
This does still exist so it shouldn't be removed

2023-07-26 16:43 UTC, Quenos commented on tastytrade/metrics.py
> -def get_risk_free_rate(session: Session) -> Decimal:
Oops, I think I integrated from an older version.
Will do the intended changes on the current version.

2023-07-26 17:21 UTC, Graeme22 commented
> After only making changes to the attributes that failed, I still get these checks to fail after the commit, at places I didn't even touch.

Looks like you removed a blank line, there should be two after each class definition.

2023-07-26 17:27 UTC, Quenos commented
All green, yeah :)

2023-07-26 18:15 UTC, Graeme22 approved these changes

2023-07-26 18:16 UTC, merged

2023-07-27 16:53 UTC, Mytak commented
I get:

File "/home/dimitar/.local/lib/python3.10/site-packages/tastytrade/metrics.py", line 114, in get_market_metrics
    return [MarketMetricInfo(**entry) for entry in data]
  File "/home/dimitar/.local/lib/python3.10/site-packages/tastytrade/metrics.py", line 114, in <listcomp>
    return [MarketMetricInfo(**entry) for entry in data]
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for MarketMetricInfo
dividend-rate-per-share
  field required (type=value_error.missing)

for Ticker META.

Could you make "dividend-rate-per-share" optional too?

2023-07-27 17:22 UTC, Graeme22 commented
Would you like to open a separate PR? @Mytak