Streamer update for the new DXFeed API
tastyware/tastytrade pull request #83
Opened 2023-08-01 15:43 UTC by Quenos

## Description
DXFeed introduced a new API 
- streamer.py and dxFeed classes updated to work with new API

All contracts stayed the same so code should be working, albeit that at current this new API has only limited capabilities.
No options e.g. Also some symbols are not working

## Related issue(s)
No issue submitted

## Pre-merge checklist
- [ ] Passing tests:
        - Happy flow and some faults are tested
           * candles are not working, also not working with the example of the DXfeed website.
- [ ] New tests added (if applicable)

2023-08-01 16:01 UTC, Quenos commented
It's a bit beyond me where to put
```
import requests
```
in order to pass the lint for the sequence of the imports

2023-08-01 16:58 UTC, Quenos commented on tastytrade/metrics.py
This file was not touched and should not be integrated.
Unsure what happened

2023-08-01 23:24 UTC, Graeme22 commented
Hey! This looks interesting, I'm excited to try it out! I noticed the other streamer in the API docs and I am intrigued.

To start off, could you make this in addition to the existing streamer instead of replacing it? I don't think it makes sense to replace the existing streamer yet, especially when the new one has more limited functionality.

Other than that, I think it would be good to get the tests passing. And the `Event` classes probably don't need to be modified; the event type is implicit in the class definition. Maybe remove that key from the dict before casting it into a class object?

> It's a bit beyond me where to put
> 
> ```
> import requests
> ```
> 
> in order to pass the lint for the sequence of the imports

You can just run `isort tastytrade` and the order will be fixed automagically.

2023-08-02 08:39 UTC, Quenos commented
- old streamer put back. Switchable using use_legacy flag on create
- Used isort, but checker still complaining. Is there a way to check this locally before pushing?

2023-08-02 09:22 UTC, Quenos commented
Need some help with these last three issues

2023-08-09 02:34 UTC, Graeme22 requested changes
Looks good! Can you clean up a few more things?

2023-08-09 02:34 UTC, Graeme22 commented on setup.py
> -
Can we get rid of all the files that weren't actually changed?

2023-08-09 02:34 UTC, Graeme22 commented on tastytrade/dxfeed/candle.py
>      #: symbol of this event
Like this one

2023-08-09 02:34 UTC, Graeme22 commented on tastytrade/streamer.py
> +        self._keepalive = asyncio.create_task(self._keepalive())
The errors are because you're using `_keepalive` as the name of the method and the variable.

2023-09-06 17:02 UTC, michaelcooke commented
@Graeme22 @Quenos is there anything I can do to help push this one along? It looks like all of the remaining items were addressed.

2023-10-23 19:28 UTC, Graeme22 commented
Hey! I've been crazy busy the last couple months, but things are calmer now so I should get the chance to tackle this in the next couple days. Thanks for being patient in the meantime!

2023-10-27 14:13 UTC, Graeme22 commented
This is more urgent than I thought, it seems like the old streamer has been moved to delayed quotes! In light of this I don't think there's any reason to keep the old streamer.

2023-10-27 14:42 UTC, michaelcooke commented
> it seems like the old streamer has been moved to delayed quotes!

It's still possible to get live quotes using dxFeed with the token and url obtained by the `/quote-streamer-tokens` endpoint. On the platform, you can switch from dxFeed to dxLink by opening settings and triple-clicking the "Currently using..." text in the general tab. Tastytrade hasn't told me how long they -- or dxFeed -- will support this data feed, but enough users are reporting issues with the websocket stream that I anticipate it will be supported for the platform for the time being.

I would bet that your quotes are being delayed arbitrarily by tastytrade; I had the same issue. You should stop any applications you personally have running using dxFeed, contact tastytrade support to complain about delayed quotes and mention you are not using the old data system, and wait for them to switch you back to live data. From there, you should be able to use dxFeed or dxLink for live data.

If it sounds confusing, arbitrary, and opaque, it's because it is.

2023-10-27 14:46 UTC, michaelcooke commented
As a testing note, `wss://tasty-openapi-ws.dxfeed.com/realtime` supports fewer event types than `wss://tasty-live-ws.dxfeed.com/realtime`.

Supported events by both feeds:
- Quote
- Candle
- Trade
- Summary
- Profile

Undocumented events supported only by live feed for platform:
- DailyCandle
- TradeETH
- Greeks
- TimeAndSale
- Underlying
- AnalyticOrder
- OptionSale
- Order
- Series
- Configuration
- Message

2023-10-27 14:53 UTC, Graeme22 commented
> As a testing note, `wss://tasty-openapi-ws.dxfeed.com/realtime` supports fewer event types than `wss://tasty-live-ws.dxfeed.com/realtime`. Tastytrade has told me this is intentional, and were surprised to hear that the extra events listed below were supported by the live platform feed.
> 
> Supported events by both feeds:
> 
> * Quote
> * Candle
> * Trade
> * Summary
> * Profile
> 
> Undocumented events supported only by live feed for platform:
> 
> * DailyCandle
> * TradeETH
> * Greeks
> * TimeAndSale
> * Underlying
> * AnalyticOrder
> * OptionSale
> * Order
> * Series
> * Configuration
> * Message

This is great stuff, thanks for researching this!

2023-10-27 14:59 UTC, Graeme22 commented
> It's still possible to get live quotes using dxFeed with the token and url obtained by the `/quote-streamer-tokens` endpoint. On the platform, you can switch from dxFeed to dxLink by opening settings and triple-clicking the "Currently using..." text in the general tab. Tastytrade hasn't told me how long they -- or dxFeed -- will support this data feed, but enough users are reporting issues with the websocket stream that I anticipate it will be supported for the platform for the time being.

That's good to know, so we have more time to get these changes integrated then. That said, we should probably get this PR moving along.

2023-10-27 15:01 UTC, Graeme22 commented
To start, can we name the streamers `DXFeedStreamer` and `DXLinkStreamer`? And update the DXLink streamer to only support the events that are currently working?

2023-11-08 18:45 UTC, Quenos commented
What is still needed here, lost track due to all the comments.

2023-11-09 00:08 UTC, Graeme22 commented
> To start, can we name the streamers `DXFeedStreamer` and `DXLinkStreamer`? And update the DXLink streamer to only support the events that are currently working?

This to start with

2023-11-15 18:19 UTC, merged